packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
overrides:
  "@next/env": npm:@varlock/nextjs-integration@1.2.2
catalog:
  typescript: ^6.0.3
  "@types/node": ^26.4.1
  varlock: 1.18.0
  lucide-react: ^1.41.0
  react: ^19.2.8
  react-dom: ^19.2.8
  "@tailwindcss/postcss": ^4.3.3
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.7
  tailwindcss: ^4.3.3
